language: python
python:
  - '3.9'
before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging
env: DJANGO_SETTINGS_MODULE="website.settings.travis"

dist: xenial
services:
  - postgresql
  - xvfb
script:
  - ./manage.py test


