dist: bionic
language: python
python:
  - '3.9'
before_script:
  - pip install -r requirements.txt
  - install-webdrivers --path website/webdrivers/
branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="website.travis"

services:
  - postgresql

script:
  - ./manage.py test

addons:
  chrome: stable
