language: python
python:
  - '3.9'
before_script:
  - pip install -r requirements.txt
  - bundle exec rails runner "Webdrivers:Chromedriver.update"
branches:
  only:
    - staging
env: DJANGO_SETTINGS_MODULE="website.settings.travis"


services:
  - postgresql

script:
  - ./manage.py test

addons:
  chrome: stable

